### ISSUE TITLE
Getting 'so.42: cannot open shared object file: No such file or directory. (LoadError) Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory' Error

### ISSUE THREAD

**Issue by SamuelBanya** [IsraelDCastro/rails-vite-tailwindcss-template#12]
Hello,

Here is the related affected environment:

- Linux Mint with Rails Version 7.0.4.3

**Related Command I Used:**
```
$ rails new clickclock --skip-webpack-install --skip-javascript -d postgresql -m https://raw.githubusercontent.com/IsraelDCastro/rails-vite-tailwindcss-template/master/template.rb --vue
```

**Related Error:**
```
/usr/share/rvm/gems/ruby-2.7.4/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory
```

**Question:**

- Any thoughts as to why this might be occurring?

This is the full traceback error I am receiving:
```
Traceback (most recent call last):
        32: from bin/rails:4:in `<main>'
        31: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        30: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        29: from /usr/share/rvm/gems/ruby-2.7.4/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
        28: from /usr/share/rvm/gems/ruby-2.7.4/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
        27: from /usr/share/rvm/gems/ruby-2.7.4/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
        26: from /usr/share/rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        25: from /usr/share/rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        24: from /usr/share/rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        23: from /usr/share/rvm/gems/ruby-2.7.4/gems/railties-7.0.4.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        22: from /usr/share/rvm/gems/ruby-2.7.4/gems/railties-7.0.4.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        21: from /usr/share/rvm/gems/ruby-2.7.4/gems/railties-7.0.4.3/lib/rails/command/actions.rb:22:in `require_application!'
        20: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        19: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        18: from /home/sam/hub/ClickClock/clickclock/config/application.rb:7:in `<main>'
        17: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.4.9/lib/bundler.rb:197:in `require'
        16: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.4.9/lib/bundler/runtime.rb:44:in `require'
        15: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.4.9/lib/bundler/runtime.rb:44:in `each'
        14: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.4.9/lib/bundler/runtime.rb:55:in `block in require'
        13: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.4.9/lib/bundler/runtime.rb:55:in `each'
        12: from /usr/share/rvm/gems/ruby-2.7.4/gems/bundler-2.4.9/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        11: from /usr/share/rvm/gems/ruby-2.7.4/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
        10: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         9: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         8: from /usr/share/rvm/gems/ruby-2.7.4/gems/ruby-vips-2.1.4/lib/ruby-vips.rb:1:in `<main>'
         7: from /usr/share/rvm/gems/ruby-2.7.4/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
         6: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         5: from /usr/share/rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         4: from /usr/share/rvm/gems/ruby-2.7.4/gems/ruby-vips-2.1.4/lib/vips.rb:570:in `<main>'
         3: from /usr/share/rvm/gems/ruby-2.7.4/gems/ruby-vips-2.1.4/lib/vips.rb:573:in `<module:Vips>'
         2: from /usr/share/rvm/gems/ruby-2.7.4/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
         1: from /usr/share/rvm/gems/ruby-2.7.4/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
/usr/share/rvm/gems/ruby-2.7.4/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory
```

**Comment by SamuelBanya** [comment]
Hey there,

Just wanted to give a quick update in that I was able to resolve this by successfully installing the related dependency via the 'apt' package manager on Linux Mint via this command:
```
$ sudo apt-get install libvips libvips-dev
```

Closing ticket, thanks!
